services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-local
    ports:
      - "5672:5672"    # AMQP port—for producers/consumers
      - "15672:15672"  # HTTP port—for management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  ingest-service:
    build:
      context: ./ingest-service
      dockerfile: Dockerfile
    container_name: ingest-service
    ports:
      - "8000:8000"    # expose FastAPI server
    volumes:
      - ./videos:/videos
    environment:
      RTSP_URL: "/videos/test.mp4"
      RABBITMQ_HOST: "rabbitmq-local"
      RABBITMQ_QUEUE: "video_frames"
      RABBITMQ_USER: user # Add this line
      RABBITMQ_PASS: password # Add this line
    depends_on:
      - rabbitmq